"use client";
import {useEffect,useState} from "react";
import { errorMessage, type Team } from "@/types/app";
import { clientApi } from "@/lib/api-client";
type Group={id:string;name:string;team_ids?:string[]};
export default function GroupBuilder({refresh=0}:{refresh?:number}){const[teams,setTeams]=useState<Team[]>([]),[groups,setGroups]=useState<Group[]>([]),[drag,setDrag]=useState<string|null>(null),[over,setOver]=useState("unassigned"),[status,setStatus]=useState("");const load=()=>Promise.all([clientApi("/teams"),clientApi("/groups")]).then(([t,g])=>{setTeams((Array.isArray(t)?t:(t as {teams?:Team[]}).teams||[]) as Team[]);setGroups((Array.isArray(g)?g:(g as {groups?:Group[]}).groups||[]).map((x:Group)=>({...x,team_ids:Array.isArray(x.team_ids)?x.team_ids:[]})))}).catch(e=>setStatus(errorMessage(e)));useEffect(()=>{void load()},[refresh]);
async function place(id:string,target:Group|null){try{await clientApi(`/teams/${id}`,{method:"PUT",body:JSON.stringify({group_id:target?.name||null})});setStatus("Saved ✓");void load()}catch(e:unknown){setStatus(errorMessage(e))}}
async function addGroup(){const name=String.fromCharCode(65+groups.length);try{await clientApi("/groups",{method:"POST",body:JSON.stringify({name,team_ids:[]})});void load()}catch(e:unknown){setStatus(errorMessage(e))}}
async function removeGroup(g:Group){const count=teams.filter(t=>t.group_id===g.name||t.group_id===`group-${g.name}`).length;if(!confirm(`Delete ${g.name}? ${count?`It contains ${count} team${count===1?"":"s"}; its group matches will also be removed.`:""}`))return;try{await clientApi(`/groups/${g.id}`,{method:"DELETE"});setStatus("Saved ✓");void load()}catch(e:unknown){setStatus(errorMessage(e))}}
const card=(t:Team)=><article draggable key={t.id} onDragStart={()=>setDrag(t.id)} className="group-builder-team"><span className="team-dot" style={{background:t.color||"#ec4899"}}/><b>{t.name}</b><label className="sr-only" htmlFor={`group-${t.id}`}>Move {t.name} to group</label><select id={`group-${t.id}`} value={t.group_id || ""} onChange={(event)=>void place(t.id, groups.find((group)=>group.name===event.target.value) || null)}><option value="">Unassigned</option>{groups.map((group)=><option key={group.id} value={group.name}>{group.name}</option>)}</select></article>;
return <section className="panel group-builder"><div className="panelhead"><div><h3>Build your groups</h3><small>Each team plays every other team in its group once. Create matches from Schedule.</small></div><span>{status}</span><button className="btn primary" onClick={addGroup}>+ Group</button></div><div className="group-builder-board"><div className={`group-builder-column ${over==="unassigned"?"drop-target":""}`} onDragOver={e=>{e.preventDefault();setOver("unassigned")}} onDrop={()=>drag&&place(drag,null)}><h4>Unassigned <em>{teams.filter(t=>!t.group_id).length}</em></h4>{teams.filter(t=>!t.group_id).map(card)}</div>{groups.map(g=><div className={`group-builder-column ${over===g.id?"drop-target":""}`} key={g.id} onDragOver={e=>{e.preventDefault();setOver(g.id)}} onDrop={()=>drag&&place(drag,g)}><h4>{g.name} <em>{teams.filter(t=>t.group_id===g.name||t.group_id===`group-${g.name}`).length}</em> <button className="danger-link" onClick={()=>void removeGroup(g)}>Delete</button></h4>{teams.filter(t=>t.group_id===g.name||t.group_id===`group-${g.name}`).map(card)}<small>Drop teams here</small></div>)}</div></section>}
