export type PublicFaqQuestion = { question: string; answer: string };
export type PublicFaqGroup = { title: string; questions: PublicFaqQuestion[] };

type FaqTournamentSettings = { start_date?: string; end_date?: string; venue_name?: string; venue_address?: string; accessibility_info?: string; show_livestream?: number };

export function getPublicFaq(tournament: FaqTournamentSettings, teamCount: number, language: "en" | "nl" = "en"): PublicFaqGroup[] {
  const nl = language === "nl";
  const dates = `${tournament.start_date || (nl ? "de gepubliceerde toernooidata" : "the published tournament dates")}${tournament.end_date ? `${nl ? " tot " : " to "}${tournament.end_date}` : ""}`;
  const venue = [tournament.venue_name, tournament.venue_address].filter(Boolean).join(", ") || (nl ? "de gepubliceerde toernooilocatie" : "the published tournament venue");
  const teams = teamCount ? `${teamCount} ${nl ? "teams zijn momenteel gepubliceerd." : "teams are currently published."}` : (nl ? "De teamlijst wordt bijgewerkt zodra teams bevestigd zijn." : "The team list will be updated as teams are confirmed.");
  const groups: PublicFaqGroup[] = [
    { title: nl ? "Over PCF BATTLE" : "About PCF BATTLE", questions: [
      { question: nl ? "Wat is PCF BATTLE?" : "What is PCF BATTLE?", answer: nl ? "PCF BATTLE is een internationaal powerchair floorballtoernooi dat teams samenbrengt voor competitieve wedstrijden in een dynamische toernooisfeer." : "PCF BATTLE is an international powerchair floorball tournament bringing teams together for competitive matches in an energetic tournament environment." },
      { question: nl ? "Wat is powerchair floorball?" : "What is powerchair floorball?", answer: nl ? "Powerchair floorball is een snelle, inclusieve teamsport voor sporters die een elektrische rolstoel gebruiken. Spelers nemen deel met floorballsticks die aan hun rolstoel zijn bevestigd of die ze in hun handen houden. De sport combineert tactisch samenspel, precisie en snelheid." : "Powerchair floorball is a fast-paced, inclusive team sport played by athletes using electric wheelchairs. Players compete with floorball sticks attached to their wheelchairs or held in their hands, combining tactical teamwork, precision, and speed." },
    ] },
    { title: nl ? "Toernooi & bezoekers" : "Tournament & Spectators", questions: [
      { question: nl ? "Wanneer en waar vindt PCF BATTLE plaats?" : "When and where does PCF BATTLE take place?", answer: nl ? `Het toernooi vindt plaats van ${dates} in ${venue}. Meer praktische informatie vind je op de pagina Praktische informatie.` : `The tournament takes place from ${dates} at ${venue}. More practical information is available on the Practical Information page.` },
      { question: nl ? "Welke teams nemen deel?" : "Which teams are participating?", answer: nl ? `Alle bevestigde teams staan vermeld bij Deelnemende teams op de website. ${teams}` : `All confirmed teams are listed in the Participating Teams section of the website. ${teams}` },
      { question: nl ? "Waar vind ik het wedstrijdschema?" : "Where can I find the match schedule?", answer: nl ? "Het volledige wedstrijdschema staat in het onderdeel Toernooi. Wedstrijdtijden en andere informatie kunnen tijdens het toernooi worden aangepast." : "The complete tournament schedule is available in the Tournament section. Match times and other information can be updated during the tournament." },
      { question: nl ? "Waar kan ik de resultaten en stand bekijken?" : "Where can I see the results and standings?", answer: nl ? "Resultaten, groepsstanden en het toernooischema worden tijdens PCF BATTLE op de website bijgewerkt." : "Results, group standings, and tournament brackets are updated on the website throughout PCF BATTLE." },
      { question: nl ? "Is PCF BATTLE toegankelijk voor toeschouwers?" : "Is PCF BATTLE open to spectators?", answer: nl ? "Ja. Toeschouwers zijn welkom om powerchair floorball live te beleven. Bekijk de pagina Praktische informatie voor informatie over de locatie en bezoekers." : "Yes. Spectators are welcome to come and experience powerchair floorball live. Please check the Practical Information page for venue and visitor details." },
      { question: nl ? "Is de locatie toegankelijk voor rolstoelgebruikers?" : "Is the venue wheelchair accessible?", answer: tournament.accessibility_info || (nl ? "Informatie over toegankelijkheid vind je op de pagina Praktische informatie. Neem vooraf contact op met de organisatie als je specifieke toegankelijkheidsbehoeften hebt." : "Accessibility information is available on the Practical Information page. Please contact the organization in advance if you have specific accessibility requirements.") },
      { question: nl ? "Worden de wedstrijden gestreamd?" : "Will the matches be livestreamed?", answer: Number(tournament.show_livestream) === 1 ? (nl ? "Ja. Wanneer livestreaming beschikbaar is, wordt de link op de Livestreampagina gepubliceerd en gedeeld via de sociale mediakanalen van PCF BATTLE." : "Yes. When livestreaming is available, the link is published on the Livestream page and shared through the PCF BATTLE social media channels.") : (nl ? "Informatie over de livestream wordt op de website gepubliceerd zodra die beschikbaar is." : "Livestream information will be published on the website when it is available.") },
    ] },
    { title: nl ? "Teams & registratie" : "Teams & Registration", questions: [
      { question: nl ? "Waar vinden teams hun toernooi-informatie?" : "Where can teams find their tournament information?", answer: nl ? "Deelnemende teams krijgen toegang tot hun persoonlijke Team Portal. Daar kunnen ze de informatie die de toernooiorganisatie nodig heeft indienen en beheren." : "Participating teams receive access to their personal Team Portal, where they can submit and manage the information required by the tournament organization." },
      { question: nl ? "Hoe kan mijn team deelnemen aan PCF BATTLE?" : "How can my team participate in PCF BATTLE?", answer: nl ? "Wanneer de inschrijvingen geopend zijn, kunnen teams zich via de PCF BATTLE-website registreren. Een registratie garandeert niet automatisch dat een team geselecteerd wordt." : "When registrations are open, teams can submit their registration through the PCF BATTLE website. Registration does not automatically guarantee selection for the tournament." },
      { question: nl ? "Hoe weten we of ons team geselecteerd is?" : "How will we know if our team has been selected?", answer: nl ? "Geselecteerde teams ontvangen een officiële bevestiging per e-mail. Later ontvangen ze een aparte uitnodiging voor hun Team Portal." : "Selected teams receive an official confirmation by email. They will later receive a separate invitation to access their Team Portal." },
      { question: nl ? "Kan ik PCF BATTLE volgen op sociale media?" : "Can I follow PCF BATTLE on social media?", answer: nl ? "Ja. Volg PCF BATTLE op Instagram voor aankondigingen, deelnemende teams, beelden achter de schermen, resultaten en andere updates." : "Yes. Follow PCF BATTLE on Instagram for tournament announcements, participating teams, behind-the-scenes content, results, and other updates." },
      { question: nl ? "Met wie kan ik contact opnemen als ik een vraag heb?" : "Who can I contact if I have a question?", answer: nl ? "Gebruik de Contactpagina om de organisatie te mailen of PCF BATTLE op sociale media te vinden." : "Use the Contact page to email the organisation or find PCF BATTLE on social media." },
    ] },
  ];
  return groups;
}
